name: Dump firmware(s)

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'URLs'
        required: true

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
    - name: Run maximize-build-space
      uses: easimon/maximize-build-space@master
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup
      run: |
        sudo apt update
        sudo apt -y install aria2 erofs-utils

    - name: Dump
      id: dump
      run: echo ${{ inputs.urls }} | xargs ./dump.sh

    - name: dump erofs
      run: |
         cd ota 
         sudo mkdir system system_ext product odm vendor
         fsck.erofs --extract=system system.img
         ls system
         fsck.erofs --extract=system_ext system_ext.img
         ls system_ext
         fsck.erofs --extract=odm odm.img 
         ls odm
         fsck.erofs --extract=vendor vendor.img 
         ls vendor
         fsck.erofs --extract=product product.img
         ls product
         
    - name: Zip
      run: |
        cd ota && sudo bash ../zip.sh
        
    - name: Upload release assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: ota/*.zip
        artifactErrorsFailBuild: true
        body: ${{ steps.dump.outputs.body }}
        tag: ${{ steps.dump.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
